# Generated by Django 4.0.1 on 2022-02-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_trainee_intakeid_remove_trainee_trackid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='intakename',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='bdate',
        ),
    ]
