# Generated by Django 4.0.1 on 2022-02-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_intake_intakename_remove_trainee_bdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='startdate',
        ),
        migrations.AddField(
            model_name='intake',
            name='intakename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trackid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
