# Generated by Django 4.0.1 on 2022-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_intake_enddate_remove_intake_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='intakename',
            field=models.CharField(max_length=30),
        ),
    ]
