# Generated by Django 4.0.1 on 2022-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_intake_intakename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='intakename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
