# Generated by Django 4.0.1 on 2022-02-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_intakename_intake_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='name',
        ),
    ]
