# Generated by Django 4.0.1 on 2022-02-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_intake_name_alter_intake_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='trackname',
        ),
    ]
